---
abstract: 'WSDL to Perl classes when building your dist'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires:
  Const::Fast: '0'
  Cwd: '0'
  Dist::Zilla::Tester: '4.101550'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Path::Class: '0'
  Test::Moose: '0'
  Test::More: '0'
  Test::Most: '0'
  Test::RequiresInternet: '0'
  perl: '5.010001'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-WSDL
provides:
  Dist::Zilla::Plugin::WSDL:
    file: lib/Dist/Zilla/Plugin/WSDL.pm
    version: '0.208'
requires:
  Dist::Zilla: '6.001'
  Dist::Zilla::Role::BeforeBuild: '0'
  Dist::Zilla::Role::Tempdir: '0'
  English: '0'
  File::Copy: '0'
  LWP::UserAgent: '0'
  Modern::Perl: '0'
  Moose: '0'
  Moose::Meta::TypeConstraint: '0'
  MooseX::AttributeShortcuts: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::Perl: '0'
  MooseX::Types::URI: '0'
  Path::Tiny: '0'
  SOAP::WSDL::Expat::WSDLParser: '0'
  SOAP::WSDL::Factory::Generator: '0'
  Tree::DAG_Node: '1.06'
  Try::Tiny: '0'
  autodie: '0'
  namespace::autoclean: '0'
  perl: '5.010001'
  utf8: '0'
resources:
  bugtracker: https://github.com/mjgardner/Dist-Zilla-Plugin-WSDL/issues
  homepage: http://metacpan.org/release/Dist-Zilla-Plugin-WSDL/
  repository: git://github.com/mjgardner/Dist-Zilla-Plugin-WSDL.git
version: '0.208'
x_generated_by_perl: v5.32.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
